var dataset = [
  {
    data_Point: "IPL",
    player_name: "Jasprit Bumrah",
    parent_series: "Indian Premier League",
    against_team: "Mumbai Indians",
    at_venue: "Wankhede Stadium, Mumbai",
    overs: "16-20",
    innings: "20",
    wickets: "25",
    runsconceded: "400",
    oversbowled: "99",
    ballsbowled: "594",
    maiden: "2",
    average: "16.5",
    economyrate: "8.23",
    strikerate: "14.25",
    bestbowling: "3/16",
    wicket3: "1",
  },
  {
    data_Point: "T20I",
    player_name: "Jasprit Bumrah",
    parent_series: "T20-I",
    against_team: "Australia",
    at_venue: "Wankhede Stadium, Mumbai",
    overs: "16-20",
    innings: "20",
    wickets: "27",
    runsconceded: "350",
    oversbowled: "99",
    ballsbowled: "594",
    maiden: "3",
    average: "15.4",
    economyrate: "3.53",
    strikerate: "15.24",
    bestbowling: "4/24",
    wicket3: "2",
  },
  {
    data_Point: "Venue",
    player_name: "Jasprit Bumrah",
    parent_series: "T20-I",
    against_team: "Australia",
    at_venue: "Wankhede Stadium, Mumbai",
    overs: "16-20",
    innings: "7",
    wickets: "17",
    runsconceded: "73",
    oversbowled: "14",
    ballsbowled: "54",
    maiden: "1",
    average: "15.4",
    economyrate: "5.21",
    strikerate: "4.29",
    bestbowling: "2/11",
    wicket3: "2",
  },
  {
    data_Point: "Opposition",
    player_name: "Jasprit Bumrah",
    parent_series: "T20-I",
    against_team: "Australia",
    at_venue: "Wankhede Stadium, Mumbai",
    overs: "16-20",
    innings: "4",
    wickets: "10",
    runsconceded: "50",
    oversbowled: "8",
    ballsbowled: "48",
    maiden: "1",
    average: "15.4",
    economyrate: "6.25",
    strikerate: "5.00",
    bestbowling: "3/19",
    wicket3: "1",
  },
];
