var teams = [
  ["Lucknow Super Giants", "lsg"],
  ["Rajasthan Royals", "rr"],
  ["Sunrisers Hyderabad", "sh"],
  ["Gujarat Titans", "gt"],
];
// var teams = [
//   ["Delhi Capitals", "dc"],
//   ["Lucknow Super Giants", "lsg"],
//   ["Rajasthan Royals", "rr"],
//   ["Sunrisers Hyderabad", "sh"],
//   ["Gujarat Titans", "gt"],
// ];

// Lucknow Super Giants
// Rajasthan Royals
// Sunrisers Hyderabad
// Gujarat Titans

// var teams = [
//   ["Delhi Capitals", "dc"],
//   ["Kolkata Knight Riders", "kkr"],
//   ["Lucknow Super Giants", "lsg"],
//   ["Mumbai Indians", "mi"],
//   ["Punjab Kings", "pk"],
//   ["Rajasthan Royals", "rr"],
//   ["Royal Challengers Bangalore", "rcb"],
//   ["Sunrisers Hyderabad", "sh"],
//   ["Rising Pune Supergiant", "rps"],
//   ["Gujarat Titans", "gt"],
// ];

//
//

var abrev = {
  pk: "Punjab Kings",
  sh: "Sunrisers Hyderabad",
  gt: "Gujarat Titans",
  lsg: "Lucknow Super Giants",
  dc: "Delhi Capitals",
  nprr: "Not Playing (RR)",
  npdc: "Not Playing (DC)",
  kkr: "Kolkata Knight Riders",
  mi: "Mumbai Indians",
  rcb: "Royal Challengers Bangalore",
  gl: "Gujarat Lions",
  rr: "Rajasthan Royals",
  rps: "Rising Pune Supergiant",
};

var bowlers = {
  pk: ["Sandeep Sharma", "Kagiso Rabada", "Odean Smith"],
  sh: ["Jason Holder"],
  lsg: ["Dushmantha Chameera", "Andrew Tye", "Avesh Khan"],
  gt: ["Mohammad Shami", "Lockie Ferguson", "Hardik Pandya"],
};

var wicketFormulaData = [
  {
    sNo: "1",
    team: "Rajasthan Royals ",
    playerName: "Trent Boult",
    "wicketDeathOvers(t20i)": "24",
    "oversBowledDeathOvers(t20i)": "44",
    "wickets/OversProbability(t20i)": "0.55",
    "wicketDeathOvers(ipl)": "43",
    "oversBowledDeathOvers(ipl)": "81",
    "wickets/OversProbability(ipl)": "0.53",
    againstTeam: "Delhi Capitals",
    "wicketDeathOvers(at)": "2",
    "oversBowledDeathOvers(at)": "6",
    "wickets/OversProbability(at)": "0.33",
    "Probability of taking wicket": "0.47",
    "overBowled(1)": "1",
    "overBowled(2)": "2",
    for1Over: "47.0",
    for2Over: "94.0",
  },
  {
    sNo: "1",
    team: "Rajasthan Royals ",
    playerName: "Trent Boult",
    "wicketDeathOvers(t20i)": "24",
    "oversBowledDeathOvers(t20i)": "44",
    "wickets/OversProbability(t20i)": "0.55",
    "wicketDeathOvers(ipl)": "43",
    "oversBowledDeathOvers(ipl)": "81",
    "wickets/OversProbability(ipl)": "0.53",
    againstTeam: "Lucknow Super Giants",
    "wicketDeathOvers(at)": "0",
    "oversBowledDeathOvers(at)": "1",
    "wickets/OversProbability(at)": "0.00",
    "Probability of taking wicket": "0.36",
    "overBowled(1)": "1",
    "overBowled(2)": "2",
    for1Over: "35.9",
    for2Over: "71.8",
  },
  {
    sNo: "1",
    team: "Rajasthan Royals ",
    playerName: "Trent Boult",
    "wicketDeathOvers(t20i)": "24",
    "oversBowledDeathOvers(t20i)": "44",
    "wickets/OversProbability(t20i)": "0.55",
    "wicketDeathOvers(ipl)": "43",
    "oversBowledDeathOvers(ipl)": "81",
    "wickets/OversProbability(ipl)": "0.53",
    againstTeam: "Rajasthan Royals",
    "wicketDeathOvers(at)": "4",
    "oversBowledDeathOvers(at)": "7",
    "wickets/OversProbability(at)": "0.57",
    "Probability of taking wicket": "0.55",
    "overBowled(1)": "1",
    "overBowled(2)": "2",
    for1Over: "54.9",
    for2Over: "109.8",
  },
  {
    sNo: "4",
    team: "Sunrisers Hyderabad",
    playerName: "Jason Holder",
    "wicketDeathOvers(t20i)": "22",
    "oversBowledDeathOvers(t20i)": "28",
    "wickets/OversProbability(t20i)": "0.79",
    "wicketDeathOvers(ipl)": "23",
    "oversBowledDeathOvers(ipl)": "27",
    "wickets/OversProbability(ipl)": "0.85",
    againstTeam: "Delhi Capitals",
    "wicketDeathOvers(at)": "1",
    "oversBowledDeathOvers(at)": "6",
    "wickets/OversProbability(at)": "0.17",
    "Probability of taking wicket": "0.60",
    "overBowled(1)": "1",
    "overBowled(2)": "2",
    for1Over: "60.1",
    for2Over: "120.3",
  },
  {
    sNo: "4",
    team: "Sunrisers Hyderabad",
    playerName: "Jason Holder",
    "wicketDeathOvers(t20i)": "22",
    "oversBowledDeathOvers(t20i)": "28",
    "wickets/OversProbability(t20i)": "0.79",
    "wicketDeathOvers(ipl)": "23",
    "oversBowledDeathOvers(ipl)": "27",
    "wickets/OversProbability(ipl)": "0.85",
    againstTeam: "Rajasthan Royals",
    "wicketDeathOvers(at)": "3",
    "oversBowledDeathOvers(at)": "4",
    "wickets/OversProbability(at)": "0.75",
    "Probability of taking wicket": "0.80",
    "overBowled(1)": "1",
    "overBowled(2)": "2",
    for1Over: "79.6",
    for2Over: "159.2",
  },
  {
    sNo: "4",
    team: "Sunrisers Hyderabad",
    playerName: "Jason Holder",
    "wicketDeathOvers(t20i)": "22",
    "oversBowledDeathOvers(t20i)": "28",
    "wickets/OversProbability(t20i)": "0.79",
    "wicketDeathOvers(ipl)": "23",
    "oversBowledDeathOvers(ipl)": "27",
    "wickets/OversProbability(ipl)": "0.85",
    againstTeam: "Sunrisers Hyderabad",
    "wicketDeathOvers(at)": "5",
    "oversBowledDeathOvers(at)": "3",
    "wickets/OversProbability(at)": "1.67",
    "Probability of taking wicket": "1.10",
    "overBowled(1)": "1",
    "overBowled(2)": "2",
    for1Over: "110.1",
    for2Over: "220.3",
  },
  {
    sNo: "5",
    team: "Gujarat Titans",
    playerName: "Mohammad Shami",
    "wicketDeathOvers(t20i)": "14",
    "oversBowledDeathOvers(t20i)": "18",
    "wickets/OversProbability(t20i)": "0.78",
    "wicketDeathOvers(ipl)": "57",
    "oversBowledDeathOvers(ipl)": "78",
    "wickets/OversProbability(ipl)": "0.73",
    againstTeam: "Delhi Capitals",
    "wicketDeathOvers(at)": "9",
    "oversBowledDeathOvers(at)": "8",
    "wickets/OversProbability(at)": "1.13",
    "Probability of taking wicket": "0.88",
    "overBowled(1)": "1",
    "overBowled(2)": "2",
    for1Over: "87.8",
    for2Over: "175.6",
  },
  {
    sNo: "5",
    team: "Gujarat Titans",
    playerName: "Mohammad Shami",
    "wicketDeathOvers(t20i)": "14",
    "oversBowledDeathOvers(t20i)": "18",
    "wickets/OversProbability(t20i)": "0.78",
    "wicketDeathOvers(ipl)": "57",
    "oversBowledDeathOvers(ipl)": "78",
    "wickets/OversProbability(ipl)": "0.73",
    againstTeam: "Lucknow Super Giants",
    "wicketDeathOvers(at)": "0",
    "oversBowledDeathOvers(at)": "1",
    "wickets/OversProbability(at)": "0.00",
    "Probability of taking wicket": "0.50",
    "overBowled(1)": "1",
    "overBowled(2)": "2",
    for1Over: "50.3",
    for2Over: "100.6",
  },
  {
    sNo: "5",
    team: "Gujarat Titans",
    playerName: "Mohammad Shami",
    "wicketDeathOvers(t20i)": "14",
    "oversBowledDeathOvers(t20i)": "18",
    "wickets/OversProbability(t20i)": "0.78",
    "wicketDeathOvers(ipl)": "57",
    "oversBowledDeathOvers(ipl)": "78",
    "wickets/OversProbability(ipl)": "0.73",
    againstTeam: "Rajasthan Royals",
    "wicketDeathOvers(at)": "11",
    "oversBowledDeathOvers(at)": "10",
    "wickets/OversProbability(at)": "1.10",
    "Probability of taking wicket": "0.87",
    "overBowled(1)": "1",
    "overBowled(2)": "2",
    for1Over: "87.0",
    for2Over: "173.9",
  },
  {
    sNo: "5",
    team: "Gujarat Titans",
    playerName: "Mohammad Shami",
    "wicketDeathOvers(t20i)": "14",
    "oversBowledDeathOvers(t20i)": "18",
    "wickets/OversProbability(t20i)": "0.78",
    "wicketDeathOvers(ipl)": "57",
    "oversBowledDeathOvers(ipl)": "78",
    "wickets/OversProbability(ipl)": "0.73",
    againstTeam: "Sunrisers Hyderabad",
    "wicketDeathOvers(at)": "6",
    "oversBowledDeathOvers(at)": "10",
    "wickets/OversProbability(at)": "0.60",
    "Probability of taking wicket": "0.70",
    "overBowled(1)": "1",
    "overBowled(2)": "2",
    for1Over: "70.3",
    for2Over: "140.6",
  },
  {
    sNo: "6",
    team: "Lucknow Super Giants",
    playerName: "Dushmantha Chameera",
    "wicketDeathOvers(t20i)": "22",
    "oversBowledDeathOvers(t20i)": "51",
    "wickets/OversProbability(t20i)": "0.43",
    "wicketDeathOvers(ipl)": "3",
    "oversBowledDeathOvers(ipl)": "7",
    "wickets/OversProbability(ipl)": "0.43",
    againstTeam: "Delhi Capitals",
    "wicketDeathOvers(at)": "0",
    "oversBowledDeathOvers(at)": "1",
    "wickets/OversProbability(at)": "0.00",
    "Probability of taking wicket": "0.29",
    "overBowled(1)": "1",
    "overBowled(2)": "2",
    for1Over: "28.7",
    for2Over: "57.3",
  },
  {
    sNo: "6",
    team: "Lucknow Super Giants",
    playerName: "Dushmantha Chameera",
    "wicketDeathOvers(t20i)": "22",
    "oversBowledDeathOvers(t20i)": "51",
    "wickets/OversProbability(t20i)": "0.43",
    "wicketDeathOvers(ipl)": "3",
    "oversBowledDeathOvers(ipl)": "7",
    "wickets/OversProbability(ipl)": "0.43",
    againstTeam: "Gujarat Titans",
    "wicketDeathOvers(at)": "0",
    "oversBowledDeathOvers(at)": "1",
    "wickets/OversProbability(at)": "0.00",
    "Probability of taking wicket": "0.29",
    "overBowled(1)": "1",
    "overBowled(2)": "2",
    for1Over: "28.7",
    for2Over: "57.3",
  },
  {
    sNo: "7",
    team: "Delhi Capitals ",
    playerName: "Shardul Thakur",
    "wicketDeathOvers(t20i)": "22",
    "oversBowledDeathOvers(t20i)": "29",
    "wickets/OversProbability(t20i)": "0.76",
    "wicketDeathOvers(ipl)": "31",
    "oversBowledDeathOvers(ipl)": "69",
    "wickets/OversProbability(ipl)": "0.45",
    againstTeam: "Delhi Capitals",
    "wicketDeathOvers(at)": "2",
    "oversBowledDeathOvers(at)": "8",
    "wickets/OversProbability(at)": "0.25",
    "Probability of taking wicket": "0.49",
    "overBowled(1)": "1",
    "overBowled(2)": "2",
    for1Over: "48.6",
    for2Over: "97.2",
  },
  {
    sNo: "7",
    team: "Delhi Capitals ",
    playerName: "Shardul Thakur",
    "wicketDeathOvers(t20i)": "22",
    "oversBowledDeathOvers(t20i)": "29",
    "wickets/OversProbability(t20i)": "0.76",
    "wicketDeathOvers(ipl)": "31",
    "oversBowledDeathOvers(ipl)": "69",
    "wickets/OversProbability(ipl)": "0.45",
    againstTeam: "Gujarat Titans",
    "wicketDeathOvers(at)": "0",
    "oversBowledDeathOvers(at)": "1",
    "wickets/OversProbability(at)": "0.00",
    "Probability of taking wicket": "0.40",
    "overBowled(1)": "1",
    "overBowled(2)": "2",
    for1Over: "40.3",
    for2Over: "80.5",
  },
  {
    sNo: "7",
    team: "Delhi Capitals ",
    playerName: "Shardul Thakur",
    "wicketDeathOvers(t20i)": "22",
    "oversBowledDeathOvers(t20i)": "29",
    "wickets/OversProbability(t20i)": "0.76",
    "wicketDeathOvers(ipl)": "31",
    "oversBowledDeathOvers(ipl)": "69",
    "wickets/OversProbability(ipl)": "0.45",
    againstTeam: "Lucknow Super Giants",
    "wicketDeathOvers(at)": "2",
    "oversBowledDeathOvers(at)": "3",
    "wickets/OversProbability(at)": "0.67",
    "Probability of taking wicket": "0.62",
    "overBowled(1)": "1",
    "overBowled(2)": "2",
    for1Over: "62.5",
    for2Over: "125.0",
  },
  {
    sNo: "7",
    team: "Delhi Capitals ",
    playerName: "Shardul Thakur",
    "wicketDeathOvers(t20i)": "22",
    "oversBowledDeathOvers(t20i)": "29",
    "wickets/OversProbability(t20i)": "0.76",
    "wicketDeathOvers(ipl)": "31",
    "oversBowledDeathOvers(ipl)": "69",
    "wickets/OversProbability(ipl)": "0.45",
    againstTeam: "Rajasthan Royals",
    "wicketDeathOvers(at)": "2",
    "oversBowledDeathOvers(at)": "6",
    "wickets/OversProbability(at)": "0.33",
    "Probability of taking wicket": "0.51",
    "overBowled(1)": "1",
    "overBowled(2)": "2",
    for1Over: "51.4",
    for2Over: "102.7",
  },
  {
    sNo: "7",
    team: "Delhi Capitals ",
    playerName: "Shardul Thakur",
    "wicketDeathOvers(t20i)": "22",
    "oversBowledDeathOvers(t20i)": "29",
    "wickets/OversProbability(t20i)": "0.76",
    "wicketDeathOvers(ipl)": "31",
    "oversBowledDeathOvers(ipl)": "69",
    "wickets/OversProbability(ipl)": "0.45",
    againstTeam: "Sunrisers Hyderabad",
    "wicketDeathOvers(at)": "7",
    "oversBowledDeathOvers(at)": "14",
    "wickets/OversProbability(at)": "0.50",
    "Probability of taking wicket": "0.57",
    "overBowled(1)": "1",
    "overBowled(2)": "2",
    for1Over: "56.9",
    for2Over: "113.9",
  },
  {
    sNo: "8",
    team: "Punjab Kings",
    playerName: "Kagiso Rabada",
    "wicketDeathOvers(t20i)": "24",
    "oversBowledDeathOvers(t20i)": "36",
    "wickets/OversProbability(t20i)": "0.67",
    "wicketDeathOvers(ipl)": "50",
    "oversBowledDeathOvers(ipl)": "69",
    "wickets/OversProbability(ipl)": "0.72",
    againstTeam: "Gujarat Titans",
    "wicketDeathOvers(at)": "4",
    "oversBowledDeathOvers(at)": "3",
    "wickets/OversProbability(at)": "1.33",
    "Probability of taking wicket": "0.91",
    "overBowled(1)": "1",
    "overBowled(2)": "2",
    for1Over: "90.8",
    for2Over: "181.6",
  },
  {
    sNo: "8",
    team: "Punjab Kings",
    playerName: "Kagiso Rabada",
    "wicketDeathOvers(t20i)": "24",
    "oversBowledDeathOvers(t20i)": "36",
    "wickets/OversProbability(t20i)": "0.67",
    "wicketDeathOvers(ipl)": "50",
    "oversBowledDeathOvers(ipl)": "69",
    "wickets/OversProbability(ipl)": "0.72",
    againstTeam: "Lucknow Super Giants",
    "wicketDeathOvers(at)": "1",
    "oversBowledDeathOvers(at)": "1",
    "wickets/OversProbability(at)": "1.00",
    "Probability of taking wicket": "0.80",
    "overBowled(1)": "1",
    "overBowled(2)": "2",
    for1Over: "79.7",
    for2Over: "159.4",
  },
  {
    sNo: "8",
    team: "Punjab Kings",
    playerName: "Kagiso Rabada",
    "wicketDeathOvers(t20i)": "24",
    "oversBowledDeathOvers(t20i)": "36",
    "wickets/OversProbability(t20i)": "0.67",
    "wicketDeathOvers(ipl)": "50",
    "oversBowledDeathOvers(ipl)": "69",
    "wickets/OversProbability(ipl)": "0.72",
    againstTeam: "Rajasthan Royals",
    "wicketDeathOvers(at)": "5",
    "oversBowledDeathOvers(at)": "7",
    "wickets/OversProbability(at)": "0.71",
    "Probability of taking wicket": "0.70",
    "overBowled(1)": "1",
    "overBowled(2)": "2",
    for1Over: "70.2",
    for2Over: "140.4",
  },
  {
    sNo: "8",
    team: "Punjab Kings",
    playerName: "Kagiso Rabada",
    "wicketDeathOvers(t20i)": "24",
    "oversBowledDeathOvers(t20i)": "36",
    "wickets/OversProbability(t20i)": "0.67",
    "wicketDeathOvers(ipl)": "50",
    "oversBowledDeathOvers(ipl)": "69",
    "wickets/OversProbability(ipl)": "0.72",
    againstTeam: "Sunrisers Hyderabad",
    "wicketDeathOvers(at)": "10",
    "oversBowledDeathOvers(at)": "13",
    "wickets/OversProbability(at)": "0.77",
    "Probability of taking wicket": "0.72",
    "overBowled(1)": "1",
    "overBowled(2)": "2",
    for1Over: "72.0",
    for2Over: "144.0",
  },
  {
    sNo: "10",
    team: "Gujarat Titans",
    playerName: "Lockie Ferguson",
    "wicketDeathOvers(t20i)": "7",
    "oversBowledDeathOvers(t20i)": "9",
    "wickets/OversProbability(t20i)": "0.78",
    "wicketDeathOvers(ipl)": "12",
    "oversBowledDeathOvers(ipl)": "32",
    "wickets/OversProbability(ipl)": "0.38",
    againstTeam: "Delhi Capitals",
    "wicketDeathOvers(at)": "2",
    "oversBowledDeathOvers(at)": "4",
    "wickets/OversProbability(at)": "0.50",
    "Probability of taking wicket": "0.55",
    "overBowled(1)": "1",
    "overBowled(2)": "2",
    for1Over: "55.1",
    for2Over: "110.2",
  },
  {
    sNo: "10",
    team: "Gujarat Titans",
    playerName: "Lockie Ferguson",
    "wicketDeathOvers(t20i)": "7",
    "oversBowledDeathOvers(t20i)": "9",
    "wickets/OversProbability(t20i)": "0.78",
    "wicketDeathOvers(ipl)": "12",
    "oversBowledDeathOvers(ipl)": "32",
    "wickets/OversProbability(ipl)": "0.38",
    againstTeam: "Lucknow Super Giants",
    "wicketDeathOvers(at)": "0",
    "oversBowledDeathOvers(at)": "2",
    "wickets/OversProbability(at)": "0.00",
    "Probability of taking wicket": "0.38",
    "overBowled(1)": "1",
    "overBowled(2)": "2",
    for1Over: "38.4",
    for2Over: "76.9",
  },
  {
    sNo: "10",
    team: "Gujarat Titans",
    playerName: "Lockie Ferguson",
    "wicketDeathOvers(t20i)": "7",
    "oversBowledDeathOvers(t20i)": "9",
    "wickets/OversProbability(t20i)": "0.78",
    "wicketDeathOvers(ipl)": "12",
    "oversBowledDeathOvers(ipl)": "32",
    "wickets/OversProbability(ipl)": "0.38",
    againstTeam: "Rajasthan Royals",
    "wicketDeathOvers(at)": "0",
    "oversBowledDeathOvers(at)": "1",
    "wickets/OversProbability(at)": "0.00",
    "Probability of taking wicket": "0.38",
    "overBowled(1)": "1",
    "overBowled(2)": "2",
    for1Over: "38.4",
    for2Over: "76.9",
  },
  {
    sNo: "10",
    team: "Gujarat Titans",
    playerName: "Lockie Ferguson",
    "wicketDeathOvers(t20i)": "7",
    "oversBowledDeathOvers(t20i)": "9",
    "wickets/OversProbability(t20i)": "0.78",
    "wicketDeathOvers(ipl)": "12",
    "oversBowledDeathOvers(ipl)": "32",
    "wickets/OversProbability(ipl)": "0.38",
    againstTeam: "Sunrisers Hyderabad",
    "wicketDeathOvers(at)": "0",
    "oversBowledDeathOvers(at)": "5",
    "wickets/OversProbability(at)": "0.00",
    "Probability of taking wicket": "0.38",
    "overBowled(1)": "1",
    "overBowled(2)": "2",
    for1Over: "38.4",
    for2Over: "76.9",
  },
  {
    sNo: "11",
    team: "Gujarat Titans",
    playerName: "Hardik Pandya",
    "wicketDeathOvers(t20i)": "14",
    "oversBowledDeathOvers(t20i)": "17",
    "wickets/OversProbability(t20i)": "0.82",
    "wicketDeathOvers(ipl)": "17",
    "oversBowledDeathOvers(ipl)": "27",
    "wickets/OversProbability(ipl)": "0.63",
    againstTeam: "Delhi Capitals",
    "wicketDeathOvers(at)": "1",
    "oversBowledDeathOvers(at)": "3",
    "wickets/OversProbability(at)": "0.33",
    "Probability of taking wicket": "0.60",
    "overBowled(1)": "1",
    "overBowled(2)": "2",
    for1Over: "59.5",
    for2Over: "119.1",
  },
  {
    sNo: "11",
    team: "Gujarat Titans",
    playerName: "Hardik Pandya",
    "wicketDeathOvers(t20i)": "14",
    "oversBowledDeathOvers(t20i)": "17",
    "wickets/OversProbability(t20i)": "0.82",
    "wicketDeathOvers(ipl)": "17",
    "oversBowledDeathOvers(ipl)": "27",
    "wickets/OversProbability(ipl)": "0.63",
    againstTeam: "Rajasthan Royals",
    "wicketDeathOvers(at)": "4",
    "oversBowledDeathOvers(at)": "5",
    "wickets/OversProbability(at)": "0.80",
    "Probability of taking wicket": "0.75",
    "overBowled(1)": "1",
    "overBowled(2)": "2",
    for1Over: "75.1",
    for2Over: "150.2",
  },
  {
    sNo: "11",
    team: "Gujarat Titans",
    playerName: "Hardik Pandya",
    "wicketDeathOvers(t20i)": "14",
    "oversBowledDeathOvers(t20i)": "17",
    "wickets/OversProbability(t20i)": "0.82",
    "wicketDeathOvers(ipl)": "17",
    "oversBowledDeathOvers(ipl)": "27",
    "wickets/OversProbability(ipl)": "0.63",
    againstTeam: "Sunrisers Hyderabad",
    "wicketDeathOvers(at)": "2",
    "oversBowledDeathOvers(at)": "2",
    "wickets/OversProbability(at)": "1.00",
    "Probability of taking wicket": "0.82",
    "overBowled(1)": "1",
    "overBowled(2)": "2",
    for1Over: "81.8",
    for2Over: "163.5",
  },
  {
    sNo: "13",
    team: "Lucknow Super Giants",
    playerName: "Andrew Tye",
    "wicketDeathOvers(t20i)": "32",
    "oversBowledDeathOvers(t20i)": "50",
    "wickets/OversProbability(t20i)": "0.64",
    "wicketDeathOvers(ipl)": "24",
    "oversBowledDeathOvers(ipl)": "37",
    "wickets/OversProbability(ipl)": "0.65",
    againstTeam: "Delhi Capitals",
    "wicketDeathOvers(at)": "2",
    "oversBowledDeathOvers(at)": "3",
    "wickets/OversProbability(at)": "0.67",
    "Probability of taking wicket": "0.65",
    "overBowled(1)": "1",
    "overBowled(2)": "2",
    for1Over: "65.2",
    for2Over: "130.4",
  },
  {
    sNo: "13",
    team: "Lucknow Super Giants",
    playerName: "Andrew Tye",
    "wicketDeathOvers(t20i)": "32",
    "oversBowledDeathOvers(t20i)": "50",
    "wickets/OversProbability(t20i)": "0.64",
    "wicketDeathOvers(ipl)": "24",
    "oversBowledDeathOvers(ipl)": "37",
    "wickets/OversProbability(ipl)": "0.65",
    againstTeam: "Rajasthan Royals",
    "wicketDeathOvers(at)": "6",
    "oversBowledDeathOvers(at)": "4",
    "wickets/OversProbability(at)": "1.50",
    "Probability of taking wicket": "0.93",
    "overBowled(1)": "1",
    "overBowled(2)": "2",
    for1Over: "93.0",
    for2Over: "185.9",
  },
  {
    sNo: "13",
    team: "Lucknow Super Giants",
    playerName: "Andrew Tye",
    "wicketDeathOvers(t20i)": "32",
    "oversBowledDeathOvers(t20i)": "50",
    "wickets/OversProbability(t20i)": "0.64",
    "wicketDeathOvers(ipl)": "24",
    "oversBowledDeathOvers(ipl)": "37",
    "wickets/OversProbability(ipl)": "0.65",
    againstTeam: "Sunrisers Hyderabad",
    "wicketDeathOvers(at)": "1",
    "oversBowledDeathOvers(at)": "5",
    "wickets/OversProbability(at)": "0.20",
    "Probability of taking wicket": "0.50",
    "overBowled(1)": "1",
    "overBowled(2)": "2",
    for1Over: "49.6",
    for2Over: "99.2",
  },
  {
    sNo: "14",
    team: "Rajasthan Royals ",
    playerName: "Navdeep Saini",
    "wicketDeathOvers(t20i)": "2",
    "oversBowledDeathOvers(t20i)": "7",
    "wickets/OversProbability(t20i)": "0.29",
    "wicketDeathOvers(ipl)": "12",
    "oversBowledDeathOvers(ipl)": "25",
    "wickets/OversProbability(ipl)": "0.48",
    againstTeam: "Delhi Capitals",
    "wicketDeathOvers(at)": "3",
    "oversBowledDeathOvers(at)": "4",
    "wickets/OversProbability(at)": "0.75",
    "Probability of taking wicket": "0.51",
    "overBowled(1)": "1",
    "overBowled(2)": "2",
    for1Over: "50.5",
    for2Over: "101.0",
  },
  {
    sNo: "14",
    team: "Rajasthan Royals ",
    playerName: "Navdeep Saini",
    "wicketDeathOvers(t20i)": "2",
    "oversBowledDeathOvers(t20i)": "7",
    "wickets/OversProbability(t20i)": "0.29",
    "wicketDeathOvers(ipl)": "12",
    "oversBowledDeathOvers(ipl)": "25",
    "wickets/OversProbability(ipl)": "0.48",
    againstTeam: "Rajasthan Royals",
    "wicketDeathOvers(at)": "0",
    "oversBowledDeathOvers(at)": "4",
    "wickets/OversProbability(at)": "0.00",
    "Probability of taking wicket": "0.26",
    "overBowled(1)": "1",
    "overBowled(2)": "2",
    for1Over: "25.5",
    for2Over: "51.0",
  },
  {
    sNo: "14",
    team: "Rajasthan Royals ",
    playerName: "Navdeep Saini",
    "wicketDeathOvers(t20i)": "2",
    "oversBowledDeathOvers(t20i)": "7",
    "wickets/OversProbability(t20i)": "0.29",
    "wicketDeathOvers(ipl)": "12",
    "oversBowledDeathOvers(ipl)": "25",
    "wickets/OversProbability(ipl)": "0.48",
    againstTeam: "Sunrisers Hyderabad",
    "wicketDeathOvers(at)": "3",
    "oversBowledDeathOvers(at)": "5",
    "wickets/OversProbability(at)": "0.60",
    "Probability of taking wicket": "0.46",
    "overBowled(1)": "1",
    "overBowled(2)": "2",
    for1Over: "45.5",
    for2Over: "91.0",
  },
  {
    sNo: "15",
    team: "Lucknow Super Giants",
    playerName: "Avesh Khan",
    "wicketDeathOvers(t20i)": "0",
    "oversBowledDeathOvers(t20i)": "2",
    "wickets/OversProbability(t20i)": "0.00",
    "wicketDeathOvers(ipl)": "18",
    "oversBowledDeathOvers(ipl)": "40",
    "wickets/OversProbability(ipl)": "0.45",
    againstTeam: "Delhi Capitals",
    "wicketDeathOvers(at)": "0",
    "oversBowledDeathOvers(at)": "3",
    "wickets/OversProbability(at)": "0.00",
    "Probability of taking wicket": "0.15",
    "overBowled(1)": "1",
    "overBowled(2)": "2",
    for1Over: "15.0",
    for2Over: "30.0",
  },
  {
    sNo: "15",
    team: "Lucknow Super Giants",
    playerName: "Avesh Khan",
    "wicketDeathOvers(t20i)": "0",
    "oversBowledDeathOvers(t20i)": "2",
    "wickets/OversProbability(t20i)": "0.00",
    "wicketDeathOvers(ipl)": "18",
    "oversBowledDeathOvers(ipl)": "40",
    "wickets/OversProbability(ipl)": "0.45",
    againstTeam: "Gujarat Titans",
    "wicketDeathOvers(at)": "1",
    "oversBowledDeathOvers(at)": "2",
    "wickets/OversProbability(at)": "0.50",
    "Probability of taking wicket": "0.32",
    "overBowled(1)": "1",
    "overBowled(2)": "2",
    for1Over: "31.7",
    for2Over: "63.3",
  },
  {
    sNo: "15",
    team: "Lucknow Super Giants",
    playerName: "Avesh Khan",
    "wicketDeathOvers(t20i)": "0",
    "oversBowledDeathOvers(t20i)": "2",
    "wickets/OversProbability(t20i)": "0.00",
    "wicketDeathOvers(ipl)": "18",
    "oversBowledDeathOvers(ipl)": "40",
    "wickets/OversProbability(ipl)": "0.45",
    againstTeam: "Rajasthan Royals",
    "wicketDeathOvers(at)": "0",
    "oversBowledDeathOvers(at)": "4",
    "wickets/OversProbability(at)": "0.00",
    "Probability of taking wicket": "0.15",
    "overBowled(1)": "1",
    "overBowled(2)": "2",
    for1Over: "15.0",
    for2Over: "30.0",
  },
  {
    sNo: "15",
    team: "Lucknow Super Giants",
    playerName: "Avesh Khan",
    "wicketDeathOvers(t20i)": "0",
    "oversBowledDeathOvers(t20i)": "2",
    "wickets/OversProbability(t20i)": "0.00",
    "wicketDeathOvers(ipl)": "18",
    "oversBowledDeathOvers(ipl)": "40",
    "wickets/OversProbability(ipl)": "0.45",
    againstTeam: "Sunrisers Hyderabad",
    "wicketDeathOvers(at)": "5",
    "oversBowledDeathOvers(at)": "4",
    "wickets/OversProbability(at)": "1.25",
    "Probability of taking wicket": "0.57",
    "overBowled(1)": "1",
    "overBowled(2)": "2",
    for1Over: "56.7",
    for2Over: "113.3",
  },
];

var ecoFormulaData = [
  {
    sNo: "1",
    team: "Rajasthan Royals",
    playerName: "Trent Boult",
    "economy(t20i)": "8.1",
    "weightage(t20i)": "0.3",
    "economy(ipl)": "8.4",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "16",
    "strikeRate(ipl)": "18.5",
    againstTeam: "Delhi Capitals",
    "economy(at)": "6.5",
    "weightage(at)": "0.3",
    "strikeRate(at)": "13.2",
    economySum: "23",
    percentageSum: "1",
    ecoFinal: "23",
    ouput: "7.7",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "7.7",
    for2Overs: "15.3",
  },
  {
    sNo: "1",
    team: "Rajasthan Royals",
    playerName: "Trent Boult",
    "economy(t20i)": "8.1",
    "weightage(t20i)": "0.3",
    "economy(ipl)": "8.4",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "16",
    "strikeRate(ipl)": "18.5",
    againstTeam: "Rajasthan Royals",
    "economy(at)": "7.9",
    "weightage(at)": "0.3",
    "strikeRate(at)": "20",
    economySum: "24.4",
    percentageSum: "1",
    ecoFinal: "24.4",
    ouput: "8.1",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "8.1",
    for2Overs: "16.3",
  },
  {
    sNo: "1",
    team: "Rajasthan Royals",
    playerName: "Trent Boult",
    "economy(t20i)": "8.1",
    "weightage(t20i)": "0.3",
    "economy(ipl)": "8.4",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "16",
    "strikeRate(ipl)": "18.5",
    againstTeam: "Sunrisers Hyderabad",
    "economy(at)": "8.2",
    "weightage(at)": "0.3",
    "strikeRate(at)": "18.8",
    economySum: "24.7",
    percentageSum: "1",
    ecoFinal: "24.7",
    ouput: "8.2",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "8.2",
    for2Overs: "16.4",
  },
  {
    sNo: "1",
    team: "Rajasthan Royals",
    playerName: "Trent Boult",
    "economy(t20i)": "8.1",
    "weightage(t20i)": "0.3",
    "economy(ipl)": "8.4",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "16",
    "strikeRate(ipl)": "18.5",
    againstTeam: "Lucknow Super Giants",
    "economy(at)": "7.5",
    "weightage(at)": "0.3",
    "strikeRate(at)": "12",
    economySum: "24",
    percentageSum: "1",
    ecoFinal: "24",
    ouput: "8",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "8",
    for2Overs: "16",
  },
  {
    sNo: "3",
    team: "Punjab Kings",
    playerName: "Sandeep Sharma",
    "economy(t20i)": "10.4",
    "weightage(t20i)": "0.3",
    "economy(ipl)": "7.8",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "42",
    "strikeRate(ipl)": "19.8",
    againstTeam: "Delhi Capitals",
    "economy(at)": "7.1",
    "weightage(at)": "0.3",
    "strikeRate(at)": "18.7",
    economySum: "25.3",
    percentageSum: "1",
    ecoFinal: "25.3",
    ouput: "8.4",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "8.4",
    for2Overs: "16.9",
  },
  {
    sNo: "3",
    team: "Punjab Kings",
    playerName: "Sandeep Sharma",
    "economy(t20i)": "10.4",
    "weightage(t20i)": "0.3",
    "economy(ipl)": "7.8",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "42",
    "strikeRate(ipl)": "19.8",
    againstTeam: "Rajasthan Royals",
    "economy(at)": "7.7",
    "weightage(at)": "0.3",
    "strikeRate(at)": "37.2",
    economySum: "26",
    percentageSum: "1",
    ecoFinal: "26",
    ouput: "8.7",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "8.7",
    for2Overs: "17.3",
  },
  {
    sNo: "3",
    team: "Punjab Kings",
    playerName: "Sandeep Sharma",
    "economy(t20i)": "10.4",
    "weightage(t20i)": "0.3",
    "economy(ipl)": "7.8",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "42",
    "strikeRate(ipl)": "19.8",
    againstTeam: "Sunrisers Hyderabad",
    "economy(at)": "8.8",
    "weightage(at)": "0.3",
    "strikeRate(at)": "21.3",
    economySum: "27",
    percentageSum: "1",
    ecoFinal: "27",
    ouput: "9",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "9",
    for2Overs: "18",
  },
  {
    sNo: "4",
    team: "Sunrisers Hyderabad",
    playerName: "Jason Holder",
    "economy(t20i)": "8.2",
    "weightage(t20i)": "0.3",
    "economy(ipl)": "8.3",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "19",
    "strikeRate(ipl)": "16.2",
    againstTeam: "Delhi Capitals",
    "economy(at)": "9.8",
    "weightage(at)": "0.3",
    "strikeRate(at)": "71.5",
    economySum: "26.2",
    percentageSum: "1",
    ecoFinal: "26.2",
    ouput: "8.7",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "8.7",
    for2Overs: "17.5",
  },
  {
    sNo: "4",
    team: "Sunrisers Hyderabad",
    playerName: "Jason Holder",
    "economy(t20i)": "8.2",
    "weightage(t20i)": "0.3",
    "economy(ipl)": "8.3",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "19",
    "strikeRate(ipl)": "16.2",
    againstTeam: "Rajasthan Royals",
    "economy(at)": "8",
    "weightage(at)": "0.3",
    "strikeRate(at)": "17.1",
    economySum: "24.4",
    percentageSum: "1",
    ecoFinal: "24.4",
    ouput: "8.1",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "8.1",
    for2Overs: "16.3",
  },
  {
    sNo: "4",
    team: "Sunrisers Hyderabad",
    playerName: "Jason Holder",
    "economy(t20i)": "8.2",
    "weightage(t20i)": "0.3",
    "economy(ipl)": "8.3",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "19",
    "strikeRate(ipl)": "16.2",
    againstTeam: "Sunrisers Hyderabad",
    "economy(at)": "8.2",
    "weightage(at)": "0.3",
    "strikeRate(at)": "21.6",
    economySum: "24.6",
    percentageSum: "1",
    ecoFinal: "24.6",
    ouput: "8.2",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "8.2",
    for2Overs: "16.4",
  },
  {
    sNo: "5",
    team: "Gujarat Titans",
    playerName: "Mohammad Shami",
    "economy(t20i)": "9.5",
    "weightage(t20i)": "0.3",
    "economy(ipl)": "8.5",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "19.8",
    "strikeRate(ipl)": "20.9",
    againstTeam: "Delhi Capitals",
    "economy(at)": "7.8",
    "weightage(at)": "0.3",
    "strikeRate(at)": "16.2",
    economySum: "25.9",
    percentageSum: "1",
    ecoFinal: "25.9",
    ouput: "8.6",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "8.6",
    for2Overs: "17.3",
  },
  {
    sNo: "5",
    team: "Gujarat Titans",
    playerName: "Mohammad Shami",
    "economy(t20i)": "9.5",
    "weightage(t20i)": "0.3",
    "economy(ipl)": "8.5",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "19.8",
    "strikeRate(ipl)": "20.9",
    againstTeam: "Rajasthan Royals",
    "economy(at)": "8.9",
    "weightage(at)": "0.3",
    "strikeRate(at)": "17.5",
    economySum: "27",
    percentageSum: "1",
    ecoFinal: "27",
    ouput: "9",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "9",
    for2Overs: "18",
  },
  {
    sNo: "5",
    team: "Gujarat Titans",
    playerName: "Mohammad Shami",
    "economy(t20i)": "9.5",
    "weightage(t20i)": "0.3",
    "economy(ipl)": "8.5",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "19.8",
    "strikeRate(ipl)": "20.9",
    againstTeam: "Sunrisers Hyderabad",
    "economy(at)": "8",
    "weightage(at)": "0.3",
    "strikeRate(at)": "22.9",
    economySum: "26.1",
    percentageSum: "1",
    ecoFinal: "26.1",
    ouput: "8.7",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "8.7",
    for2Overs: "17.4",
  },
  {
    sNo: "5",
    team: "Gujarat Titans",
    playerName: "Mohammad Shami",
    "economy(t20i)": "9.5",
    "weightage(t20i)": "0.3",
    "economy(ipl)": "8.5",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "19.8",
    "strikeRate(ipl)": "20.9",
    againstTeam: "Lucknow Super Giants",
    "economy(at)": "6.3",
    "weightage(at)": "0.3",
    "strikeRate(at)": "8",
    economySum: "24.3",
    percentageSum: "1",
    ecoFinal: "24.3",
    ouput: "8.1",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "8.1",
    for2Overs: "16.2",
  },
  {
    sNo: "6",
    team: "Lucknow Super Giants",
    playerName: "Dushmantha Chameera",
    "economy(t20i)": "8",
    "weightage(t20i)": "0.3",
    "economy(ipl)": "9.6",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "21.3",
    "strikeRate(ipl)": "21.6",
    againstTeam: "Rajasthan Royals",
    "economy(at)": "5.5",
    "weightage(at)": "0.3",
    "strikeRate(at)": "-",
    economySum: "23",
    percentageSum: "1",
    ecoFinal: "23",
    ouput: "7.7",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "7.7",
    for2Overs: "15.3",
  },
  {
    sNo: "6",
    team: "Lucknow Super Giants",
    playerName: "Dushmantha Chameera",
    "economy(t20i)": "8",
    "weightage(t20i)": "0.3",
    "economy(ipl)": "9.6",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "21.3",
    "strikeRate(ipl)": "21.6",
    againstTeam: "Gujarat Titans",
    "economy(at)": "7.3",
    "weightage(at)": "0.3",
    "strikeRate(at)": "9",
    economySum: "24.9",
    percentageSum: "1",
    ecoFinal: "24.9",
    ouput: "8.3",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "8.3",
    for2Overs: "16.6",
  },
  {
    sNo: "7",
    team: "Delhi Capitals",
    playerName: "Shardul Thakur",
    "economy(t20i)": "9.2",
    "weightage(t20i)": "0.3",
    "economy(ipl)": "8.9",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "15.3",
    "strikeRate(ipl)": "19.3",
    againstTeam: "Delhi Capitals",
    "economy(at)": "9.9",
    "weightage(at)": "0.3",
    "strikeRate(at)": "23.7",
    economySum: "28",
    percentageSum: "1",
    ecoFinal: "28",
    ouput: "9.3",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "9.3",
    for2Overs: "18.6",
  },
  {
    sNo: "7",
    team: "Delhi Capitals",
    playerName: "Shardul Thakur",
    "economy(t20i)": "9.2",
    "weightage(t20i)": "0.3",
    "economy(ipl)": "8.9",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "15.3",
    "strikeRate(ipl)": "19.3",
    againstTeam: "Rajasthan Royals",
    "economy(at)": "8.1",
    "weightage(at)": "0.3",
    "strikeRate(at)": "15.6",
    economySum: "26.2",
    percentageSum: "1",
    ecoFinal: "26.2",
    ouput: "8.7",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "8.7",
    for2Overs: "17.4",
  },
  {
    sNo: "7",
    team: "Delhi Capitals",
    playerName: "Shardul Thakur",
    "economy(t20i)": "9.2",
    "weightage(t20i)": "0.3",
    "economy(ipl)": "8.9",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "15.3",
    "strikeRate(ipl)": "19.3",
    againstTeam: "Sunrisers Hyderabad",
    "economy(at)": "9.8",
    "weightage(at)": "0.3",
    "strikeRate(at)": "28.5",
    economySum: "27.9",
    percentageSum: "1",
    ecoFinal: "27.9",
    ouput: "9.3",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "9.3",
    for2Overs: "18.6",
  },
  {
    sNo: "7",
    team: "Delhi Capitals",
    playerName: "Shardul Thakur",
    "economy(t20i)": "9.2",
    "weightage(t20i)": "0.3",
    "economy(ipl)": "8.9",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "15.3",
    "strikeRate(ipl)": "19.3",
    againstTeam: "Lucknow Super Giants",
    "economy(at)": "7.9",
    "weightage(at)": "0.3",
    "strikeRate(at)": "22",
    economySum: "26",
    percentageSum: "1",
    ecoFinal: "26",
    ouput: "8.7",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "8.7",
    for2Overs: "17.3",
  },
  {
    sNo: "7",
    team: "Delhi Capitals",
    playerName: "Shardul Thakur",
    "economy(t20i)": "9.2",
    "weightage(t20i)": "0.3",
    "economy(ipl)": "8.9",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "15.3",
    "strikeRate(ipl)": "19.3",
    againstTeam: "Gujarat Titans",
    "economy(at)": "10.5",
    "weightage(at)": "0.3",
    "strikeRate(at)": "-",
    economySum: "28.6",
    percentageSum: "1",
    ecoFinal: "28.6",
    ouput: "9.5",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "9.5",
    for2Overs: "19.1",
  },
  {
    sNo: "8",
    team: "Punjab Kings",
    playerName: "Kagiso Rabada",
    "economy(t20i)": "8.6",
    "weightage(t20i)": "0.3",
    "economy(ipl)": "8.2",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "17.8",
    "strikeRate(ipl)": "15",
    againstTeam: "Rajasthan Royals",
    "economy(at)": "7.9",
    "weightage(at)": "0.3",
    "strikeRate(at)": "13.1",
    economySum: "24.7",
    percentageSum: "1",
    ecoFinal: "24.7",
    ouput: "8.2",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "8.2",
    for2Overs: "16.5",
  },
  {
    sNo: "8",
    team: "Punjab Kings",
    playerName: "Kagiso Rabada",
    "economy(t20i)": "8.6",
    "weightage(t20i)": "0.3",
    "economy(ipl)": "8.2",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "17.8",
    "strikeRate(ipl)": "15",
    againstTeam: "Sunrisers Hyderabad",
    "economy(at)": "9",
    "weightage(at)": "0.3",
    "strikeRate(at)": "13.7",
    economySum: "25.7",
    percentageSum: "1",
    ecoFinal: "25.7",
    ouput: "8.6",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "8.6",
    for2Overs: "17.2",
  },
  {
    sNo: "8",
    team: "Punjab Kings",
    playerName: "Kagiso Rabada",
    "economy(t20i)": "8.6",
    "weightage(t20i)": "0.3",
    "economy(ipl)": "8.2",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "17.8",
    "strikeRate(ipl)": "15",
    againstTeam: "Gujarat Titans",
    "economy(at)": "8.8",
    "weightage(at)": "0.3",
    "strikeRate(at)": "12",
    economySum: "25.5",
    percentageSum: "1",
    ecoFinal: "25.5",
    ouput: "8.5",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "8.5",
    for2Overs: "17",
  },
  {
    sNo: "9",
    team: "Delhi Capitals",
    playerName: "Anrich Nortje",
    "economy(t20i)": "6.8",
    "weightage(t20i)": "0.3",
    "economy(ipl)": "7.8",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "19.4",
    "strikeRate(ipl)": "16.5",
    againstTeam: "Rajasthan Royals",
    "economy(at)": "6.3",
    "weightage(at)": "0.3",
    "strikeRate(at)": "14.4",
    economySum: "20.9",
    percentageSum: "1",
    ecoFinal: "20.9",
    ouput: "7",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "7",
    for2Overs: "13.9",
  },
  {
    sNo: "9",
    team: "Delhi Capitals",
    playerName: "Anrich Nortje",
    "economy(t20i)": "6.8",
    "weightage(t20i)": "0.3",
    "economy(ipl)": "7.8",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "19.4",
    "strikeRate(ipl)": "16.5",
    againstTeam: "Sunrisers Hyderabad",
    "economy(at)": "7.8",
    "weightage(at)": "0.3",
    "strikeRate(at)": "32",
    economySum: "22.4",
    percentageSum: "1",
    ecoFinal: "22.4",
    ouput: "7.5",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "7.5",
    for2Overs: "14.9",
  },
  {
    sNo: "9",
    team: "Delhi Capitals",
    playerName: "Anrich Nortje",
    "economy(t20i)": "6.8",
    "weightage(t20i)": "0.3",
    "economy(ipl)": "7.8",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "19.4",
    "strikeRate(ipl)": "16.5",
    againstTeam: "Lucknow Super Giants",
    "economy(at)": "15",
    "weightage(at)": "0.3",
    "strikeRate(at)": "-",
    economySum: "29.6",
    percentageSum: "1",
    ecoFinal: "29.6",
    ouput: "9.9",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "9.9",
    for2Overs: "19.7",
  },
  {
    sNo: "10",
    team: "Gujarat Titans",
    playerName: "Lockie Ferguson",
    "economy(t20i)": "7.1",
    "weightage(t20i)": "0.3",
    "economy(ipl)": "8.2",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "13",
    "strikeRate(ipl)": "19.5",
    againstTeam: "Delhi Capitals",
    "economy(at)": "8",
    "weightage(at)": "0.3",
    "strikeRate(at)": "14",
    economySum: "23.3",
    percentageSum: "1",
    ecoFinal: "23.3",
    ouput: "7.8",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "7.8",
    for2Overs: "15.5",
  },
  {
    sNo: "10",
    team: "Gujarat Titans",
    playerName: "Lockie Ferguson",
    "economy(t20i)": "7.1",
    "weightage(t20i)": "0.3",
    "economy(ipl)": "8.2",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "13",
    "strikeRate(ipl)": "19.5",
    againstTeam: "Rajasthan Royals",
    "economy(at)": "5.1",
    "weightage(at)": "0.3",
    "strikeRate(at)": "8",
    economySum: "20.4",
    percentageSum: "1",
    ecoFinal: "20.4",
    ouput: "6.8",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "6.8",
    for2Overs: "13.6",
  },
  {
    sNo: "10",
    team: "Gujarat Titans",
    playerName: "Lockie Ferguson",
    "economy(t20i)": "7.1",
    "weightage(t20i)": "0.3",
    "economy(ipl)": "8.2",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "13",
    "strikeRate(ipl)": "19.5",
    againstTeam: "Sunrisers Hyderabad",
    "economy(at)": "7.9",
    "weightage(at)": "0.3",
    "strikeRate(at)": "24",
    economySum: "23.2",
    percentageSum: "1",
    ecoFinal: "23.2",
    ouput: "7.7",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "7.7",
    for2Overs: "15.5",
  },
  {
    sNo: "10",
    team: "Gujarat Titans",
    playerName: "Lockie Ferguson",
    "economy(t20i)": "7.1",
    "weightage(t20i)": "0.3",
    "economy(ipl)": "8.2",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "13",
    "strikeRate(ipl)": "19.5",
    againstTeam: "Lucknow Super Giants",
    "economy(at)": "6",
    "weightage(at)": "0.3",
    "strikeRate(at)": "-",
    economySum: "21.3",
    percentageSum: "1",
    ecoFinal: "21.3",
    ouput: "7.1",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "7.1",
    for2Overs: "14.2",
  },
  {
    sNo: "11",
    team: "Gujarat Titans",
    playerName: "Hardik Pandya",
    "economy(t20i)": "8.2",
    "weightage(t20i)": "0.3",
    "economy(ipl)": "8.9",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "20",
    "strikeRate(ipl)": "21.3",
    againstTeam: "Delhi Capitals",
    "economy(at)": "8.3",
    "weightage(at)": "0.3",
    "strikeRate(at)": "25",
    economySum: "25.4",
    percentageSum: "1",
    ecoFinal: "25.4",
    ouput: "8.5",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "8.5",
    for2Overs: "16.9",
  },
  {
    sNo: "11",
    team: "Gujarat Titans",
    playerName: "Hardik Pandya",
    "economy(t20i)": "8.2",
    "weightage(t20i)": "0.3",
    "economy(ipl)": "8.9",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "20",
    "strikeRate(ipl)": "21.3",
    againstTeam: "Rajasthan Royals",
    "economy(at)": "9.3",
    "weightage(at)": "0.3",
    "strikeRate(at)": "17.6",
    economySum: "26.5",
    percentageSum: "1",
    ecoFinal: "26.5",
    ouput: "8.8",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "8.8",
    for2Overs: "17.6",
  },
  {
    sNo: "11",
    team: "Gujarat Titans",
    playerName: "Hardik Pandya",
    "economy(t20i)": "8.2",
    "weightage(t20i)": "0.3",
    "economy(ipl)": "8.9",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "20",
    "strikeRate(ipl)": "21.3",
    againstTeam: "Sunrisers Hyderabad",
    "economy(at)": "8.4",
    "weightage(at)": "0.3",
    "strikeRate(at)": "19",
    economySum: "25.5",
    percentageSum: "1",
    ecoFinal: "25.5",
    ouput: "8.5",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "8.5",
    for2Overs: "17",
  },
  {
    sNo: "11",
    team: "Gujarat Titans",
    playerName: "Hardik Pandya",
    "economy(t20i)": "8.2",
    "weightage(t20i)": "0.3",
    "economy(ipl)": "8.9",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "20",
    "strikeRate(ipl)": "21.3",
    againstTeam: "Lucknow Super Giants",
    "economy(at)": "9.3",
    "weightage(at)": "0.3",
    "strikeRate(at)": "-",
    economySum: "26.4",
    percentageSum: "1",
    ecoFinal: "26.4",
    ouput: "8.8",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "8.8",
    for2Overs: "17.6",
  },
  {
    sNo: "13",
    team: "Lucknow Super Giants",
    playerName: "Andrew Tye",
    "economy(t20i)": "8.8",
    "weightage(t20i)": "0.3",
    "economy(ipl)": "8.6",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "14.5",
    "strikeRate(ipl)": "16.3",
    againstTeam: "Delhi Capitals",
    "economy(at)": "9.4",
    "weightage(at)": "0.3",
    "strikeRate(at)": "30",
    economySum: "26.7",
    percentageSum: "1",
    ecoFinal: "26.7",
    ouput: "8.9",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "8.9",
    for2Overs: "17.8",
  },
  {
    sNo: "13",
    team: "Lucknow Super Giants",
    playerName: "Andrew Tye",
    "economy(t20i)": "8.8",
    "weightage(t20i)": "0.3",
    "economy(ipl)": "8.6",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "14.5",
    "strikeRate(ipl)": "16.3",
    againstTeam: "Rajasthan Royals",
    "economy(at)": "7.3",
    "weightage(at)": "0.3",
    "strikeRate(at)": "8",
    economySum: "24.6",
    percentageSum: "1",
    ecoFinal: "24.6",
    ouput: "8.2",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "8.2",
    for2Overs: "16.4",
  },
  {
    sNo: "13",
    team: "Lucknow Super Giants",
    playerName: "Andrew Tye",
    "economy(t20i)": "8.8",
    "weightage(t20i)": "0.3",
    "economy(ipl)": "8.6",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "14.5",
    "strikeRate(ipl)": "16.3",
    againstTeam: "Sunrisers Hyderabad",
    "economy(at)": "7.5",
    "weightage(at)": "0.3",
    "strikeRate(at)": "36",
    economySum: "24.8",
    percentageSum: "1",
    ecoFinal: "24.8",
    ouput: "8.3",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "8.3",
    for2Overs: "16.6",
  },
  {
    sNo: "14",
    team: "Rajasthan Royals",
    playerName: "Navdeep Saini",
    "economy(t20i)": "7.2",
    "weightage(t20i)": "0.3",
    "economy(ipl)": "8.7",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "15.2",
    "strikeRate(ipl)": "31.1",
    againstTeam: "Delhi Capitals",
    "economy(at)": "10.5",
    "weightage(at)": "0.3",
    "strikeRate(at)": "22",
    economySum: "26.4",
    percentageSum: "1",
    ecoFinal: "26.4",
    ouput: "8.8",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "8.8",
    for2Overs: "17.6",
  },
  {
    sNo: "14",
    team: "Rajasthan Royals",
    playerName: "Navdeep Saini",
    "economy(t20i)": "7.2",
    "weightage(t20i)": "0.3",
    "economy(ipl)": "8.7",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "15.2",
    "strikeRate(ipl)": "31.1",
    againstTeam: "Rajasthan Royals",
    "economy(at)": "8.8",
    "weightage(at)": "0.3",
    "strikeRate(at)": "78",
    economySum: "24.6",
    percentageSum: "1",
    ecoFinal: "24.6",
    ouput: "8.2",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "8.2",
    for2Overs: "16.4",
  },
  {
    sNo: "14",
    team: "Rajasthan Royals",
    playerName: "Navdeep Saini",
    "economy(t20i)": "7.2",
    "weightage(t20i)": "0.3",
    "economy(ipl)": "8.7",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "15.2",
    "strikeRate(ipl)": "31.1",
    againstTeam: "Sunrisers Hyderabad",
    "economy(at)": "9.1",
    "weightage(at)": "0.3",
    "strikeRate(at)": "16.4",
    economySum: "25",
    percentageSum: "1",
    ecoFinal: "25",
    ouput: "8.3",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "8.3",
    for2Overs: "16.6",
  },
  {
    sNo: "15",
    team: "Lucknow Super Giants",
    playerName: "Avesh Khan",
    "economy(t20i)": "8.1",
    "weightage(t20i)": "0.3",
    "economy(ipl)": "8.2",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "24",
    "strikeRate(ipl)": "17.7",
    againstTeam: "Delhi Capitals",
    "economy(at)": "7.9",
    "weightage(at)": "0.3",
    "strikeRate(at)": "42",
    economySum: "24.2",
    percentageSum: "1",
    ecoFinal: "24.2",
    ouput: "8.1",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "8.1",
    for2Overs: "16.1",
  },
  {
    sNo: "15",
    team: "Lucknow Super Giants",
    playerName: "Avesh Khan",
    "economy(t20i)": "8.1",
    "weightage(t20i)": "0.3",
    "economy(ipl)": "8.2",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "24",
    "strikeRate(ipl)": "17.7",
    againstTeam: "Rajasthan Royals",
    "economy(at)": "9.1",
    "weightage(at)": "0.3",
    "strikeRate(at)": "16.8",
    economySum: "25.5",
    percentageSum: "1",
    ecoFinal: "25.5",
    ouput: "8.5",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "8.5",
    for2Overs: "17",
  },
  {
    sNo: "15",
    team: "Lucknow Super Giants",
    playerName: "Avesh Khan",
    "economy(t20i)": "8.1",
    "weightage(t20i)": "0.3",
    "economy(ipl)": "8.2",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "24",
    "strikeRate(ipl)": "17.7",
    againstTeam: "Sunrisers Hyderabad",
    "economy(at)": "8.8",
    "weightage(at)": "0.3",
    "strikeRate(at)": "12.9",
    economySum: "25.2",
    percentageSum: "1",
    ecoFinal: "25.2",
    ouput: "8.4",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "8.4",
    for2Overs: "16.8",
  },
  {
    sNo: "15",
    team: "Lucknow Super Giants",
    playerName: "Avesh Khan",
    "economy(t20i)": "8.1",
    "weightage(t20i)": "0.3",
    "economy(ipl)": "8.2",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "24",
    "strikeRate(ipl)": "17.7",
    againstTeam: "Gujarat Titans",
    "economy(at)": "9",
    "weightage(at)": "0.3",
    "strikeRate(at)": "22",
    economySum: "25.4",
    percentageSum: "1",
    ecoFinal: "25.4",
    ouput: "8.5",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "8.5",
    for2Overs: "16.9",
  },
  {
    sNo: "16",
    team: "Punjab Kings",
    playerName: "Odean Smith",
    "economy(t20i)": "11.1",
    "weightage(t20i)": "0.3",
    "economy(ipl)": "11.9",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "21.4",
    "strikeRate(ipl)": "15",
    againstTeam: "Sunrisers Hyderabad",
    "economy(at)": "8",
    "weightage(at)": "0.3",
    "strikeRate(at)": "-",
    economySum: "31",
    percentageSum: "1",
    ecoFinal: "31",
    ouput: "10.3",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "10.3",
    for2Overs: "20.7",
  },
  {
    sNo: "16",
    team: "Punjab Kings",
    playerName: "Odean Smith",
    "economy(t20i)": "11.1",
    "weightage(t20i)": "0.3",
    "economy(ipl)": "11.9",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "21.4",
    "strikeRate(ipl)": "15",
    againstTeam: "Gujarat Titans",
    "economy(at)": "11.7",
    "weightage(at)": "0.3",
    "strikeRate(at)": "-",
    economySum: "34.6",
    percentageSum: "1",
    ecoFinal: "34.6",
    ouput: "11.5",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "11.5",
    for2Overs: "23.1",
  },
  {
    sNo: "17",
    team: "Rajasthan Royals",
    playerName: "Prasidh Krishna",
    "economy(t20i)": "",
    "weightage(t20i)": "",
    "economy(ipl)": "9.2",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "",
    "strikeRate(ipl)": "25.4",
    againstTeam: "Delhi Capitals",
    "economy(at)": "9",
    "weightage(at)": "0.3",
    "strikeRate(at)": "75",
    economySum: "18.2",
    percentageSum: "0.7",
    ecoFinal: "27.3",
    ouput: "9.1",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "9.1",
    for2Overs: "18.2",
  },
  {
    sNo: "17",
    team: "Rajasthan Royals",
    playerName: "Prasidh Krishna",
    "economy(t20i)": "",
    "weightage(t20i)": "",
    "economy(ipl)": "9.2",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "",
    "strikeRate(ipl)": "25.4",
    againstTeam: "Rajasthan Royals",
    "economy(at)": "8.8",
    "weightage(at)": "0.3",
    "strikeRate(at)": "18.3",
    economySum: "17.9",
    percentageSum: "0.7",
    ecoFinal: "26.9",
    ouput: "9",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "9",
    for2Overs: "17.9",
  },
  {
    sNo: "17",
    team: "Rajasthan Royals",
    playerName: "Prasidh Krishna",
    "economy(t20i)": "",
    "weightage(t20i)": "",
    "economy(ipl)": "9.2",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "",
    "strikeRate(ipl)": "25.4",
    againstTeam: "Sunrisers Hyderabad",
    "economy(at)": "8.4",
    "weightage(at)": "0.3",
    "strikeRate(at)": "15",
    economySum: "17.6",
    percentageSum: "0.7",
    ecoFinal: "26.3",
    ouput: "8.8",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "8.8",
    for2Overs: "17.5",
  },
  {
    sNo: "17",
    team: "Rajasthan Royals",
    playerName: "Prasidh Krishna",
    "economy(t20i)": "",
    "weightage(t20i)": "",
    "economy(ipl)": "9.2",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "",
    "strikeRate(ipl)": "25.4",
    againstTeam: "Lucknow Super Giants",
    "economy(at)": "8.8",
    "weightage(at)": "0.3",
    "strikeRate(at)": "24",
    economySum: "17.9",
    percentageSum: "0.7",
    ecoFinal: "26.8",
    ouput: "8.9",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "8.9",
    for2Overs: "17.9",
  },
  {
    sNo: "17",
    team: "Rajasthan Royals",
    playerName: "Prasidh Krishna",
    "economy(t20i)": "",
    "weightage(t20i)": "",
    "economy(ipl)": "9.2",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "",
    "strikeRate(ipl)": "25.4",
    againstTeam: "Gujarat Titans",
    "economy(at)": "8.8",
    "weightage(at)": "0.3",
    "strikeRate(at)": "-",
    economySum: "17.9",
    percentageSum: "0.7",
    ecoFinal: "26.8",
    ouput: "8.9",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "8.9",
    for2Overs: "17.9",
  },
  {
    sNo: "18",
    team: "Punjab Kings",
    playerName: "Arshdeep Singh",
    "economy(t20i)": "",
    "weightage(t20i)": "",
    "economy(ipl)": "8.6",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "",
    "strikeRate(ipl)": "18.2",
    againstTeam: "Delhi Capitals",
    "economy(at)": "8.7",
    "weightage(at)": "0.3",
    "strikeRate(at)": "36",
    economySum: "17.3",
    percentageSum: "0.7",
    ecoFinal: "25.9",
    ouput: "8.6",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "8.6",
    for2Overs: "17.3",
  },
  {
    sNo: "18",
    team: "Punjab Kings",
    playerName: "Arshdeep Singh",
    "economy(t20i)": "",
    "weightage(t20i)": "",
    "economy(ipl)": "8.6",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "",
    "strikeRate(ipl)": "18.2",
    againstTeam: "Rajasthan Royals",
    "economy(at)": "9.6",
    "weightage(at)": "0.3",
    "strikeRate(at)": "9",
    economySum: "18.2",
    percentageSum: "0.7",
    ecoFinal: "27.3",
    ouput: "9.1",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "9.1",
    for2Overs: "18.2",
  },
  {
    sNo: "18",
    team: "Punjab Kings",
    playerName: "Arshdeep Singh",
    "economy(t20i)": "",
    "weightage(t20i)": "",
    "economy(ipl)": "8.6",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "",
    "strikeRate(ipl)": "18.2",
    againstTeam: "Sunrisers Hyderabad",
    "economy(at)": "7.8",
    "weightage(at)": "0.3",
    "strikeRate(at)": "20.1",
    economySum: "16.4",
    percentageSum: "0.7",
    ecoFinal: "24.6",
    ouput: "8.2",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "8.2",
    for2Overs: "16.4",
  },
  {
    sNo: "18",
    team: "Punjab Kings",
    playerName: "Arshdeep Singh",
    "economy(t20i)": "",
    "weightage(t20i)": "",
    "economy(ipl)": "8.6",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "",
    "strikeRate(ipl)": "18.2",
    againstTeam: "Gujarat Titans",
    "economy(at)": "7.8",
    "weightage(at)": "0.3",
    "strikeRate(at)": "-",
    economySum: "16.4",
    percentageSum: "0.7",
    ecoFinal: "24.5",
    ouput: "8.2",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "8.2",
    for2Overs: "16.4",
  },
  {
    sNo: "19",
    team: "Gujarat Titans",
    playerName: "Yash Dayal",
    "economy(t20i)": "",
    "weightage(t20i)": "",
    "economy(ipl)": "8.2",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "",
    "strikeRate(ipl)": "22.3",
    againstTeam: "Rajasthan Royals",
    "economy(at)": "10",
    "weightage(at)": "0.3",
    "strikeRate(at)": "8",
    economySum: "18.2",
    percentageSum: "0.7",
    ecoFinal: "27.3",
    ouput: "9.1",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "9.1",
    for2Overs: "18.2",
  },
  {
    sNo: "20",
    team: "Delhi Capitals",
    playerName: "Chetan Sakariya",
    "economy(t20i)": "9.3",
    "weightage(t20i)": "",
    "economy(ipl)": "10",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "22",
    "strikeRate(ipl)": "12",
    againstTeam: "Delhi Capitals",
    "economy(at)": "8.3",
    "weightage(at)": "0.3",
    "strikeRate(at)": "24",
    economySum: "27.5",
    percentageSum: "0.7",
    ecoFinal: "41.3",
    ouput: "13.8",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "13.8",
    for2Overs: "27.5",
  },
  {
    sNo: "20",
    team: "Delhi Capitals",
    playerName: "Chetan Sakariya",
    "economy(t20i)": "9.3",
    "weightage(t20i)": "",
    "economy(ipl)": "10",
    "weightage(ipl)": "0.3",
    "strikeRate(t20i)": "22",
    "strikeRate(ipl)": "12",
    againstTeam: "Sunrisers Hyderabad",
    "economy(at)": "8.8",
    "weightage(at)": "0.3",
    "strikeRate(at)": "48",
    economySum: "28",
    percentageSum: "0.7",
    ecoFinal: "42",
    ouput: "14",
    "oversBowled(1)": "1",
    "oversBowled(2)": "2",
    for1Over: "14",
    for2Overs: "28",
  },
];
